{"name": "test_login_user[17647352440-yy123456-False-200002-用户名或密码错误]", "status": "broken", "statusDetails": {"message": "AttributeError: 'dict' object has no attribute 'json'", "trace": "self = <testcases.api_test.test_01_login_erp.TestUserLogin object at 0x000001DD85BC81F0>\nbase_url = 'https://erp-qa.qdjk.xyz', username = '17647352440'\npassword = 'yy123456', except_result = 'False', except_code = '200002'\nexcept_msg = '用户名或密码错误'\n\n    @allure.story(\"用例--登录用户\")\n    @pytest.mark.parametrize(\"username, password, except_result, except_code, except_msg\",\n                             login_data[\"test_login_user\"])\n    def test_login_user(self,base_url, username, password, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n>       result = login_erp_user(base_url,username, password)\n\ntest_01_login_erp.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nbaseurl = 'https://erp-qa.qdjk.xyz', username = '17647352440'\npassword = 'yy123456'\n\n    def login_erp_user(baseurl, username, password):\n        \"\"\"\n        登录用户\n        :param username: 用户名\n        :param password: 密码\n        :return: 自定义的关键字返回结果 result\n        \"\"\"\n        url = baseurl + \"/erp-auth/auth/loginpassword\"\n        print(\"url:\"+url)\n        result = ResultBase()\n        payload = {\n            \"account\": username,\n            \"password\": password\n        }\n        header = {\n            \"Content-Type\": \"application/json\"\n        }\n        res = baseapi.all_send_requests(method=\"post\", url=url, json=payload, headers=header)\n        print(\"res:\")\n        print(res)\n>       print(\"res.json:\"+res.json())\nE       AttributeError: 'dict' object has no attribute 'json'\n\n..\\..\\operation\\user.py:25: AttributeError"}, "attachments": [{"name": "log", "source": "91a38ee3-b502-4bfe-94eb-b4e493beeecb-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "234bfa95-54e9-4eeb-a7b9-d5507e5bbea1-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "73fef600-90ce-40f6-a59d-a311c8d146cd-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'17647352440'"}, {"name": "password", "value": "'yy123456'"}, {"name": "except_result", "value": "'False'"}, {"name": "except_code", "value": "'200002'"}, {"name": "except_msg", "value": "'用户名或密码错误'"}], "start": 1694411924154, "stop": 1694411924808, "uuid": "0faeb131-2f1d-4757-8617-ecabfd0a8e90", "historyId": "c34e0cd68573d7a4c0dd7563c1b60da5", "testCaseId": "80c254abc9876d28cea0e8148b92d53d", "fullName": "testcases.api_test.test_01_login_erp.TestUserLogin#test_login_user", "labels": [{"name": "story", "value": "用例--登录用户"}, {"name": "feature", "value": "用户登录模块"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_01_login_erp"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "WIN-FOCJ805QQO5"}, {"name": "thread", "value": "19792-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_01_login_erp"}]}