{"name": "test_login_user[17647352440-yy123456-False-200002-用户名或密码错误]", "status": "broken", "statusDetails": {"message": "AttributeError: 'dict' object has no attribute 'text'", "trace": "self = <testcases.api_test.test_01_login_erp.TestUserLogin object at 0x00000256A32FB790>\nbase_url = 'https://erp-qa.qdjk.xyz', username = '17647352440'\npassword = 'yy123456', except_result = 'False', except_code = '200002'\nexcept_msg = '用户名或密码错误'\n\n    @allure.story(\"用例--登录用户\")\n    @pytest.mark.parametrize(\"username, password, except_result, except_code, except_msg\",\n                             login_data[\"test_login_user\"])\n    def test_login_user(self,base_url, username, password, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n>       result = login_erp_user(base_url,username, password)\n\ntest_01_login_erp.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nbase_url = 'https://erp-qa.qdjk.xyz', username = '17647352440'\npassword = 'yy123456'\n\n    def login_erp_user(base_url, username, password):\n        \"\"\"\n        登录用户\n        :param username: 用户名\n        :param password: 密码\n        :return: 自定义的关键字返回结果 result\n        \"\"\"\n        url = base_url + \"/erp-auth/auth/loginpassword\"\n        result = ResultBase()\n        payload = {\n            \"account\": username,\n            \"password\": password\n        }\n        header = {\n            \"Content-Type\": \"application/json\"\n        }\n        res = baseapi.all_send_requests(method=\"post\", url=url, json=payload, headers=header)\n        result.success = False\n        if res[\"result\"][\"code\"] == 200:\n            result.success = True\n            result.token = res[\"data\"][\"token\"]\n        else:\n            result.error = \"接口返回码是 【 {} 】, 返回信息：{} \".format(res[\"result\"][\"code\"], res[\"result\"][\"message\"])\n        result.msg = res[\"result\"][\"message\"]\n        result.response = res\n>       logger.info(\"登录用户 ==>> 返回结果 ==>> {}\".format(result.response.text))\nE       AttributeError: 'dict' object has no attribute 'text'\n\n..\\..\\operation\\user.py:30: AttributeError"}, "attachments": [{"name": "log", "source": "7224d8e7-7144-43bc-9f60-45e502725301-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "9a4123b0-8beb-44ad-9c76-ace79b0b7ac2-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'17647352440'"}, {"name": "password", "value": "'yy123456'"}, {"name": "except_result", "value": "'False'"}, {"name": "except_code", "value": "'200002'"}, {"name": "except_msg", "value": "'用户名或密码错误'"}], "start": 1694411424958, "stop": 1694411426025, "uuid": "e2bdf64b-8d04-44c7-bd8c-9777fc143440", "historyId": "c34e0cd68573d7a4c0dd7563c1b60da5", "testCaseId": "80c254abc9876d28cea0e8148b92d53d", "fullName": "testcases.api_test.test_01_login_erp.TestUserLogin#test_login_user", "labels": [{"name": "epic", "value": "针对单个接口的测试"}, {"name": "story", "value": "用例--登录用户"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "用户登录模块"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_01_login_erp"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "WIN-FOCJ805QQO5"}, {"name": "thread", "value": "14864-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_01_login_erp"}]}